version: '3'
services:
  miner016:
    build: .
    ports:
      - "18400:18443"
      - "18500:18444"
    expose: 
      - "18444"
    command: [ "-addnode=node0161:18444", "-addnode=node0162:18444"]
  node016l:
    build: .
    ports:
      - "18401:18443"
      - "18501:18444"
    expose: 
      - "18444"
    command: [ "-addnode=miner016:18444", "-addnode=node0162:18444"]
  node0162:
    build: .
    ports:
      - "18402:18443"
      - "18502:18444"
    expose: 
      - "18444"
    command: [ "-addnode=node0161:18444", "-addnode=miner016:18444"]
